### ISSUE TITLE
STMonadTrans-0.3.4 test suite failure

### ISSUE THREAD

**Issue by peti** [josefs/STMonadTrans#4]
Citing from http://hydra.cryp.to/build/2050179/nixlog/2/raw:

~~~
Running 1 test suites...
Test suite foo: RUNNING...
Prelude.read: no parse
~~~~

**Comment by josefs** [comment]
How can I go about replicating this? Given that you're using nix, is there a nix expression you could send me that I can run to tickle this bug, @peti ?

I expect this is a bug in Cabal because I'm not using Prelude.read anywhere. That said, I'm new to the test-suite functionality of Cabal so I might have gotten something wrong.

**Comment by peti** [comment]
Run

```
nix-build "<nixpkgs>" -A haskellPackages.STMonadTrans
```

to re-produce the build with Nix. This assumes that the default Nixpkgs branch is `master` or `unstable`. The same issue _might_ exist in the `release-16.09` branch but I haven't actually tested that.

**Comment by bennofs** [comment]
Submitted as a cabal bug in haskell/cabal#4270

**Comment by josefs** [comment]
Thanks for looking into this issue @bennofs .

**Comment by andreasabel** [comment]
> Submitted as a cabal bug in [haskell/cabal#4270](https://github.com/haskell/cabal/issues/4270)

Following the recipe there, I cannot reproduce the failure any longer.
Closing, thanks to upstream for the fixes.
